VERDICT: FIX findings=7

| ID | sev | file:line | defect (one sentence) | fix (one sentence) |
|---|---|---|---|---|
| G1 | high | plan_v2.md:122 (deploy row), gate=10 | The deploy command `go build -o "$HOME/.local/libexec/bd-real.new" ./cmd/bd/` carries no `-ldflags`, and `resolveCommitHash` (`cmd/bd/version.go:116-130`) reads only the `main.Commit` ldflag before falling back to a `vcs.revision` build setting that a plain `go build -o` does not stamp here — I built the current tree that exact way and `bd version --json` printed only `{"branch","build","version"}` with no `commit` key, so gate 10's `test -n "$BD_COMMIT"` fails and `commit-match` can never print, failing the locked "Done-includes-deploy: yes … `bd version --json` commit equals HEAD" check in `manager_log.md:24`. | Change the Phase 4 deploy row to `go build -ldflags="-X main.Commit=$(git rev-parse HEAD) -X main.Branch=$(git rev-parse --abbrev-ref HEAD)" -o "$HOME/.local/libexec/bd-real.new" ./cmd/bd/ && mv …`, matching `Makefile:41`. |
| G2 | high | plan_v2.md:83 (`issues.go` change row), plan_v2.md:106 (`importer.go` NOT-affected row) | `child_counters.parent_id` is `REFERENCES issues(id)` (`migrations/014_child_counters_table.go:17-21`) and foreign keys are enforced on every connection (`store.go:99-113` sets `_pragma=foreign_keys(ON)`; I confirmed an insert for a missing parent returns `FOREIGN KEY constraint failed (19)`), while the default orphan mode is `OrphanAllow` (`config.go:60,68`) which lets `EnsureIDs` (`ids.go:233`) admit a hierarchical child whose parent is absent — I imported a one-line JSONL containing only `orph-abc.7` into a fresh DB and it succeeded today, but under the plan `insertIssues`' per-parent floor upsert would violate the FK and abort the whole depth batch with `error creating depth-1 issues`, turning a working import into a hard failure. | Add to the `issues.go` change row that the floor upsert is skipped when the parent row is absent (guard on an `EXISTS` check, or `INSERT … SELECT … WHERE EXISTS (SELECT 1 FROM issues WHERE id = ?)`), and say so in the `importer.go` NOT-affected row. |
| G3 | med | plan_v2.md:78 (Phase 1 gate) | Phase 1 removes `GetNextChildID` from `internal/storage/storage.go:164` and from both implementations, but its two production callers, `cmd/bd/create.go:169` and `internal/rpc/server_issues_epics.go:143`, are not touched until Phase 2, so Phase 1's gate `go build ./... && go vet ./...` clean cannot pass and the builder hits an unsatisfiable checkpoint (this is R1's F2 in a new place: the test rewrites moved, the production callers did not). | Move the `cmd/bd/create.go` and `internal/rpc/server_issues_epics.go` rows from Phase 2 into Phase 1 (leaving `rpc_test.go` in Phase 2), or reduce Phase 1's gate to `go test ./internal/storage/... -short` with the build gate first appearing in Phase 2. |
| G4 | med | plan_v2.md:206 (gate row 1), gate=1, gate=7 | Because `insertIssue` now raises the floor on every hierarchical insert, gate 1's setup no longer produces the lagging counter its row claims ("Build a repo with floor 1 and children 1-4"): the three `create --id repro-abc.{2,3,4}` calls leave the floor at 4, so `max(floor, scan)+1 = 5` is reached by the floor alone, and gate 7's import likewise leaves a populated counter row — meaning the allocator's scan, whose only remaining named job is repairing pre-change databases such as farmplanner's floor 33 against 43 children, is never exercised by any gate or by a Phase 3 test that can be reached through a real command. | Add a ship gate row that runs `sqlite3 "$DB" "UPDATE child_counters SET last_child=1 WHERE parent_id='repro-abc';"` and then `create --parent repro-abc`, expecting an ID above the highest existing child, and correct row 1's wording to describe the floor the new binary actually leaves. |
| G5 | med | gate=8 | The concurrency gate discards stderr and accepts `total -ge 2`, so if six of the eight parallel `create --parent` runs fail (for example on `SQLITE_BUSY` after `beginImmediateWithRetry`'s five retries in `transaction.go:52`) only two IDs land in `$C`, they are trivially distinct, and the block prints `unique=yes` while the property under test went untested. | Change the condition to `[ "$total" = 8 ] && [ "$total" = "$uniq" ]` so a failed create fails the gate. |
| G6 | med | plan_v2.md:105 (`batch_ops.go` NOT-affected row) | The row's stated reason for keeping `checkForExistingIDs` — "its error names the offending ID, which a raw UNIQUE violation does not" — stops being true once the plan's own insert returns `issue %s already exists`, leaving three mechanisms for one guarantee on the batch path: `EnsureIDs` already rejects in-batch duplicates and existing IDs (`ids.go:186-199`), `checkForExistingIDs` repeats both (`batch_ops.go:105-153`, called at `:265`), and the strict insert now aborts the same transaction with a message that names the ID. | Add a change row deleting `checkForExistingIDs` and its call at `batch_ops.go:265` (the strict insert inside the batch's single `BEGIN IMMEDIATE` transaction covers both the existing-ID and the in-batch-duplicate cases with an error that names the ID), and drop the `batch_ops.go` NOT-affected row. |
| G7 | low | plan_v2.md:73, plan_v2.md:83 | Extending the exported `IsUniqueConstraintError` (`util.go:48`) to also match `constraint failed: UNIQUE` is dead code: the driver this repo uses is `github.com/ncruces/go-sqlite3` (`go.mod:12`, `store.go:17`), whose message I measured as `sqlite3: constraint failed: UNIQUE constraint failed: z.id`, which already contains the single substring the exported helper tests, so both call sites (`importer.go:430`, `:472`) match unchanged. | Keep `util.go:48` exactly as it is; the change reduces to deleting the unexported `isUniqueConstraintError` (`issues.go:12-20`) and pointing its two former uses at the exported one. |
